services:
  - type: web
    name: app-BIC
    env: python
    buildCommand: pip install -r requirements.txt && python importar_csv.py
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
